SELECT * 
FROM SUPERMARKET_SALES;

# 1. SUPERMARKET PEAK DAYS
SELECT DATE, DAYNAME(DATE) AS DAY_OF_WEEK,
ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM SUPERMARKET_SALES
GROUP BY DATE
ORDER BY TOTAL_SALES DESC
LIMIT 3
;

# 2.INCOME BY BRANCH
SELECT BRANCH, ROUND(SUM(GROSS_INCOME),2) AS TOTAL_GROSS_INCOME
FROM SUPERMARKET_SALES
GROUP BY BRANCH
;

# 3. WORST SALES DAYS
SELECT DATE,
DAYNAME(DATE) AS DAY_OF_WEEK,
ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM SUPERMARKET_SALES
GROUP BY DATE
ORDER BY TOTAL_SALES ASC	
LIMIT 3
;

# 4. SALES TREND
SELECT monthname(DATE) AS MONTH,
ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM SUPERMARKET_SALES
GROUP BY MONTH
ORDER BY TOTAL_SALES
;

# 5. PRODUCT_LINE BY SALES
SELECT PRODUCT_LINE, ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM SUPERMARKET_SALES
GROUP BY PRODUCT_LINE
;

# 6. TOTAL PROFIT AFTER EXPENSES
SELECT CONCAT('EGP ', ROUND(SUM(GROSS_INCOME),2)) AS TOTAL_PROFIT_BEFORE_EXPENSES
FROM SUPERMARKET_SALES;

# 7. TOTAL REVENUE
SELECT ROUND(SUM(SALES),2) FROM SUPERMARKET_SALES;

# 8. PROFIT MARGIN (HOW MUCH IS KEPT FROM EVERY EGP OF SALES)
SELECT ROUND(SUM(GROSS_INCOME)/SUM(SALES) *100,2) AS PROFIT_MARGIN
FROM SUPERMARKET_SALES;

# 9. AVERAGE ORDER VALUE (HOW MUCH A CUSTOMER SPENDS PER ORDER ON AVERAGE)
SELECT ROUND(SUM(SALES)/COUNT(DISTINCT INVOICE_ID),2) AS AVG_ORDER_VALUE		
FROM SUPERMARKET_SALES;